grpc:
  server:
    port: 7443
keystore:
  path: server.jks
  pass: serverpass
truststore:
  path: trust.jks
  pass: trustpass
keycloak:
  key-url: https://localhost:8443/realms/twitter
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://twitter:twitter@localhost:27017/twitter
