grpc:
  server:
    port: 8080
keystore:
  path: server.jks
  pass: serverpass
truststore:
  path: trust.jks
  pass: trustpass
keycloak:
  key-url: http://localhost:8082/realms/twitter
  key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2kCxpzr7BBvFtcjgDepVaKiO2j9Huy7a2AOEjjw6fdISBsQDNCmHlQ4k/1mnUIfxgJZMMMW5jy5Z+C7+kTtDk0p8bVRtcaNnEElN5ORQsW2gGAlx8ARQGgV1+6L2GAOE+2vB9T2bd3x+TbRKXPjjNTSLSah4OxMvaKbif88a0j+qY8Vc4d0T1ayJd517Qq8kDNLqwm5OK9KoJeRkluOBdh6dUcUlTv4eYelTRMZrzyHiLkG11d/Zeb6F+Q/4/8FGPVpgm5x1SPxhjjLTNkbnbD7oALrw7jMu8klqHyRqVNfm2S+tQeh/3VCDTQGNFMuExkEIteKToy4MitjFy/PP+QIDAQAB
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://twitter:twitter@localhost:27017/twitter